# Generated by Django 4.2.30 on 2026-05-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannu_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='Tannu Tailoring & Fashion Classes', max_length=200)),
                ('trainer_name', models.CharField(default='Tanisha Pathan', max_length=100)),
                ('udyam_no', models.CharField(default='UDYAM-GJ-XXXXXXXX', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('course_rate', models.CharField(default='499', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institute Settings',
                'verbose_name_plural': 'Institute Settings',
            },
        ),
    ]
